# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "firstapp"
client_id = "5ca6e49f377c55c24a2af787bdabfc34"
application_url = "https://pricing-resolutions-have-partly.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pricing-resolutions-have-partly.trycloudflare.com/auth/callback",
  "https://pricing-resolutions-have-partly.trycloudflare.com/auth/shopify/callback",
  "https://pricing-resolutions-have-partly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-d7b54670.myshopify.com"
